<div class="hero-unit">
    <h1>ZF API First Application</h1>
    <p>Hero image here</p>
</div>

<div class="row">
    <div class="span12">
        <h2>Getting Started</h2>
        <p>It it important that your application be put into development mode in order to start using the ZF API First Administration screens to assist building your app.</p>
        <p>Currently, your application <b><?= (class_exists('ZF\ApiFirstAdmin\Module', false)) ? 'IS' : 'IS NOT' ?></b> in development mode.  Here are some instructions on how to do it:</p>
    </div>

</div>

<!--<div class="row"> -->
<!-- -->
<!--    <div class="span4">-->
<!--        <h2>--><?php //echo $this->translate('Follow Development') ?><!--</h2>-->
<!--        <p>--><?php //echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?><!--</p>-->
<!--        <p><a class="btn btn-success" href="http://framework.zend.com/zf2" target="_blank">--><?php //echo $this->translate('ZF2 Development Portal') ?><!-- &raquo;</a></p>-->
<!--    </div>-->
<!-- -->
<!--    <div class="span4">-->
<!--        <h2>--><?php //echo $this->translate('Discover Modules') ?><!--</h2>-->
<!--        <p>--><?php //echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?><!--</p>-->
<!--        <p><a class="btn btn-success" href="http://modules.zendframework.com/" target="_blank">--><?php //echo $this->translate('Explore ZF2 Modules') ?><!-- &raquo;</a></p>-->
<!--   </div>-->
<!-- -->
<!--   <div class="span4">-->
<!--       <h2>--><?php //echo $this->translate('Help &amp; Support') ?><!--</h2>-->
<!--       <p>--><?php //echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?><!--</p>-->
<!--       <p><a class="btn btn-success" href="http://webchat.freenode.net?channels=zftalk" target="_blank">--><?php //echo $this->translate('Ping us on IRC') ?><!-- &raquo;</a></p>-->
<!--   </div>-->
<!--</div> -->
